### ISSUE TITLE
"the command 'pip' is not found... " in ubuntu 20.04

### ISSUE THREAD

**Issue by developer-sp** [themayankjha/JAKYM#11]
When I type `pip install simpleaudio` or `pip --version`
"the command 'pip' is not found... "
Maybe why I never run python 2.
Could you cover it in readme for new users that have this problem?
Any workaround would be good too.
Thank you for the create this!

**Comment by themayankjha** [comment]
Hello! It seems to me that you don't have pip installed on your computer. I think Ubuntu 20.04 already comes with python3 pre-installed and uses python3 and pip3 to reference them.

you can verify python installation by :- ```python3 --version```
and  pip installation by :- ```pip3 --version```

if it still says python3 or pip3 not found, here is how you can install python and pip.
Update Your System - ```sudo apt update && sudo apt upgrade```
For python3 use - ```sudo apt install python3```
For pip3 use -```sudo apt install python3-pip```

and you can then continue to install simpleaudio using ```pip3 install simpleaudio```
