### ISSUE TITLE
Add song after music starts

### ISSUE THREAD

**Issue by lodenrogue** [themayankjha/JAKYM#3]
How can I add a song after music has started? 

Seems like I can add 1 song and music starts playing but I can't add more songs.

**Comment by themayankjha** [comment]
Hello loden, You can add the song right after the music starts playing just type the name of the song. the player works on an independent thread and the command window is always active.

**Comment by lodenrogue** [comment]
For me it seems to be running on a single thread? I can't type after a song starts. If I hit enter the same line repeats:

![Screenshot from 2021-04-04 12-22-26](https://user-images.githubusercontent.com/2889651/113515191-f1140a00-9540-11eb-879f-968ae2e79f30.jpg)

**Comment by lodenrogue** [comment]
You're right it does add the new song but the words I type don't appear

**Comment by themayankjha** [comment]
I think this is an issue of not having simpleaudio installed, hence jakym uses ffplay to play the music.
Installing simpleaudio will remove this behaviour.

https://github.com/themayankjha/JAKYM#installing-simpleaudio-optional-on-linux.

I think It's time to make the documentation better.

**Comment by themayankjha** [comment]
I noticed you are using both jakym and python -m jakym. It can be called by using any of those commands. during initial testing, I had trouble calling just jakym hence for redundancy I added it as a python module too. It's again time to improve the docs I guess.

**Comment by lodenrogue** [comment]
I just created an empty directory with the app name. I did a pip install, I didn't pull the code in there.

**Comment by themayankjha** [comment]
Did you manage to fix it? Does installing simpleaudio help with this?

**Comment by lodenrogue** [comment]
Yes this is resolved now by installing simpleaudio and running as:
```
jakym
```

instead of 

```
python -m jakym
```

**Comment by themayankjha** [comment]
Awesome I will work on improving the documentation a bit more!

Closing this Issue!
