### ISSUE TITLE
How to properly exit?

### ISSUE THREAD

**Issue by lodenrogue** [themayankjha/JAKYM#4]
I currently using ctrl-c to exit the application. I have to press it twice for some reason (maybe something to do with the threads). Is there a better way to exit?

**Comment by themayankjha** [comment]
just type 'exit' in the command window. even if the music is playing it will force close the thread that plays music and clean up all the downloaded files.

**Comment by lodenrogue** [comment]
Typing exit tries to download a song after a song is already playing. Also, I just tried to force quit with ctrl-c and it exited but the song is still playing in the background.

**Comment by themayankjha** [comment]
this is very strange. I have never had this issue could you provide me with any screenshots? and can you try just calling jakym without python -m jakym and trying it again?

**Comment by lodenrogue** [comment]
> this is very strange. I have never had this issue could you provide me with any screenshots? and can you try just calling jakym without python -m jakym and trying it again?

That worked. I needed to install simpleaudio and run it without python -m. It exits properly now and typing works as expected.

**Comment by themayankjha** [comment]
Awesome! I am closing this Issue then.
