### ISSUE TITLE
Simple and very useful!

### ISSUE THREAD

**Issue by mohad12211** [themayankjha/JAKYM#9]
I was having some problems with spotify, and I was about to search for replacement players that doesn't require premium account, this program is perfect, I can play youtube songs and spotify songs! and through the command line! 

-  I would suggest adding the ability to play a playlist with a single command, without the need to run the program then type spotify then type the playlist link, this will be very useful
- adding skipping songs and looping playlist.

if you accept PR I would be happy to try to contribute!

**Comment by themayankjha** [comment]
Hello! Thank you for such amazing words! Yes, I accept PR's
Single command playlist would actually be very cool indeed and skipping songs and looping too.
I'm currently working on next patch and it would be very helpful if you could contribute towards these features!

**Comment by themayankjha** [comment]
Hello, I have added the ability to instantly play a playlist in a single command. I wasn't active due to exams but the work is underway now. also skipping,pausing songs is currently quite tricky. I will work on that soon

**Comment by themayankjha** [comment]
Hello! I have added the functionality to skip and loop along with various other playback controls, you can check out the readme for all the commands!

closing the issue.
